#ifndef COMMON_H
#define COMMON_H

/*
 * Commmon functionality/variables
 * used throughout
*/

static const char *VERSION = "v1.1";
#define UPDATE_STEP_SIZE 2

typedef int BOOL;
#define TRUE  1
#define FALSE 0

/* keyboard keys */
#define W          17
#define S          31
#define UP_ARROW   72
#define DOWN_ARROW 80
#define PAUSE      25
#define SPACE      57
#define ENTER      28
#define ESC        1
/* */

#endif /* COMMON_H */
